/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long int
#endif

int evaluate_constraints(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem);
void evaluate_constraints_incref(void);
void evaluate_constraints_decref(void);
casadi_int evaluate_constraints_n_out(void);
casadi_int evaluate_constraints_n_in(void);
const char* evaluate_constraints_name_in(casadi_int i);
const char* evaluate_constraints_name_out(casadi_int i);
const casadi_int* evaluate_constraints_sparsity_in(casadi_int i);
const casadi_int* evaluate_constraints_sparsity_out(casadi_int i);
int evaluate_constraints_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
