/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) evaluate_constraints_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[64] = {60, 1, 0, 60, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59};
static const casadi_int casadi_s2[34] = {30, 1, 0, 30, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29};

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

/* evaluate_constraints:(i0[3],i1[60])->(o0[30]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a2, a3;
  a0=arg[1] ? arg[1][0] : 0;
  a0=casadi_sq(a0);
  a1=arg[1] ? arg[1][1] : 0;
  a1=casadi_sq(a1);
  a0=(a0+a1);
  a1=2.2500000000000000e+00;
  a0=(a0-a1);
  a2=0.;
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1] ? arg[1][2] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][3] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1] ? arg[1][4] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][5] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1] ? arg[1][6] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][7] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1] ? arg[1][8] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][9] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1] ? arg[1][10] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][11] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[1] ? arg[1][12] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][13] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[1] ? arg[1][14] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][15] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[1] ? arg[1][16] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][17] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[1] ? arg[1][18] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][19] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[1] ? arg[1][20] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][21] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[1] ? arg[1][22] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][23] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][11]=a0;
  a0=arg[1] ? arg[1][24] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][25] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][12]=a0;
  a0=arg[1] ? arg[1][26] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][27] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][13]=a0;
  a0=arg[1] ? arg[1][28] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][29] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][14]=a0;
  a0=arg[1] ? arg[1][30] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][31] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][15]=a0;
  a0=arg[1] ? arg[1][32] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][33] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][16]=a0;
  a0=arg[1] ? arg[1][34] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][35] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][17]=a0;
  a0=arg[1] ? arg[1][36] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][37] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][18]=a0;
  a0=arg[1] ? arg[1][38] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][39] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][19]=a0;
  a0=arg[1] ? arg[1][40] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][41] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][20]=a0;
  a0=arg[1] ? arg[1][42] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][43] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][21]=a0;
  a0=arg[1] ? arg[1][44] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][45] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][22]=a0;
  a0=arg[1] ? arg[1][46] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][47] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][23]=a0;
  a0=arg[1] ? arg[1][48] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][49] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][24]=a0;
  a0=arg[1] ? arg[1][50] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][51] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][25]=a0;
  a0=arg[1] ? arg[1][52] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][53] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][26]=a0;
  a0=arg[1] ? arg[1][54] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][55] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][27]=a0;
  a0=arg[1] ? arg[1][56] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][57] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][28]=a0;
  a0=arg[1] ? arg[1][58] : 0;
  a0=casadi_sq(a0);
  a3=arg[1] ? arg[1][59] : 0;
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=(a0-a1);
  a0=casadi_fmax(a0,a2);
  a0=casadi_sq(a0);
  if (res[0]!=0) res[0][29]=a0;
  return 0;
}

int evaluate_constraints(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

void evaluate_constraints_incref(void) {
}

void evaluate_constraints_decref(void) {
}

casadi_int evaluate_constraints_n_in(void) { return 2;}

casadi_int evaluate_constraints_n_out(void) { return 1;}

const char* evaluate_constraints_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* evaluate_constraints_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* evaluate_constraints_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* evaluate_constraints_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

int evaluate_constraints_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
