/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) integrator_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};

/* integrator:(i0[3],i1[2])->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=5.0000000000000003e-02;
  a1=1.6666666666666666e-01;
  a2=arg[1] ? arg[1][0] : 0;
  a3=arg[0] ? arg[0][2] : 0;
  a4=cos(a3);
  a4=(a2*a4);
  a4=(a1*a4);
  a5=3.3333333333333331e-01;
  a6=5.0000000000000000e-01;
  a7=arg[1] ? arg[1][1] : 0;
  a8=(a6*a7);
  a8=(a0*a8);
  a8=(a8+a3);
  a9=cos(a8);
  a9=(a2*a9);
  a9=(a5*a9);
  a4=(a4+a9);
  a6=(a6*a7);
  a6=(a0*a6);
  a6=(a6+a3);
  a9=cos(a6);
  a9=(a2*a9);
  a9=(a5*a9);
  a4=(a4+a9);
  a9=(a0*a7);
  a9=(a9+a3);
  a10=cos(a9);
  a10=(a2*a10);
  a10=(a1*a10);
  a4=(a4+a10);
  a4=(a0*a4);
  a10=arg[0] ? arg[0][0] : 0;
  a4=(a4+a10);
  if (res[0]!=0) res[0][0]=a4;
  a4=sin(a3);
  a4=(a2*a4);
  a4=(a1*a4);
  a8=sin(a8);
  a8=(a2*a8);
  a8=(a5*a8);
  a4=(a4+a8);
  a6=sin(a6);
  a6=(a2*a6);
  a6=(a5*a6);
  a4=(a4+a6);
  a9=sin(a9);
  a2=(a2*a9);
  a2=(a1*a2);
  a4=(a4+a2);
  a4=(a0*a4);
  a2=arg[0] ? arg[0][1] : 0;
  a4=(a4+a2);
  if (res[0]!=0) res[0][1]=a4;
  a4=(a1*a7);
  a2=(a5*a7);
  a4=(a4+a2);
  a5=(a5*a7);
  a4=(a4+a5);
  a1=(a1*a7);
  a4=(a4+a1);
  a0=(a0*a4);
  a0=(a0+a3);
  if (res[0]!=0) res[0][2]=a0;
  return 0;
}

int integrator(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

void integrator_incref(void) {
}

void integrator_decref(void) {
}

casadi_int integrator_n_in(void) { return 2;}

casadi_int integrator_n_out(void) { return 1;}

const char* integrator_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* integrator_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* integrator_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* integrator_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

int integrator_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
